#!/usr/bin/perl -w
use strict;
use warnings;
use Data::Dumper;

my $indent = -1;

my ($link, $time);

my $class0 = "field";
my @classes = qw(romaji nihongo english attack);

while (defined (my $line=<STDIN>)) {
	chomp $line;
	next if $line =~ /^\s*#/;
	my ($link1, $time1, @fields) = split /\t/, $line, -1;
	if ($link1) {
		$link = $link1;
	}
	if ($time1) {
		$time = $time1;
	}
	$fields[0] ||= '';
	$fields[0] =~ s/^(\.*)//;
	my $row = "";
	my $i = 0;
	for (@fields) {
		my $class = $classes[$i++] || "";
		$row .= qq{ <span class="$class0 $class">$_</span>};
	}
	my $indent1 = length($1);
	while ($indent < $indent1) {
		print "<ul>\n";
		++$indent;
	}
	while ($indent > $indent1) {
		print "</ul>\n";
		--$indent;
	}
	if (@fields <= 1 && $fields[0] eq '') {
		print qq{<li style="visibility: hidden;">\n};
	} elsif ($time ne "" && $time ne "-" && $link =~ m{watch\?v=}) {
		my $yt_time = "${time}s";
		$yt_time =~ s/(.*):/$1m/;
		$yt_time =~ s/(.*):/$1h/;
		print qq{<li><A href="$link&t=$yt_time#t=$yt_time">$row</A>\n};
	} elsif ($link =~ m{://}) {
		print qq{<li><A href="$link">$row</A>\n};
	} else {
		print qq{<li>$row\n};
	}
}
while ($indent > -1) {
	print "</ul>\n";
	--$indent;
}
