#!/usr/bin/env python

import sys, os, cgi, cgitb, re, datetime, smtplib, getpass, socket
cgitb.enable(display=0, logdir="log/cgi_logs")

comments_email = "comments@swatkins.fastmail.fm"

done_headers = False

def headers(type="text/html;charset=UTF-8"):
	global done_headers
	if done_headers:
		return
	print "Content-Type: %s\x0d\x0a\x0d\x0a" % type,
	done_headers = True

def error(code, status, *args):
	msg = ' '.join(str(x) for x in args)
	print "Status: %s %s\x0d\x0a\x0d\x0a%s" % (code, status, msg)
	exit(1)

def bad_request(*args):
	error(400, "Bad Request", *args)

def path_okay(path):
	return not (len(path) > 500 or path.startswith('/') or '..' in path or re.search(r'[^-/_.,+A-Za-z0-9]', path))

def text_to_html(s):
	s = cgi.escape(s)
	s = re.sub(r'\r', '', s)
	s = re.sub(r'\s*$', '', s)
	s = re.sub(r'\n', '<br>\n', s)
	return s

def append_comment(file_path, comment):
	try:
		with open(file_path, "a") as f:
			f.write(comment)
	except IOError as e:
		error(403, "Forbidden", e)

def send_comment_email(email_to, page, comment):
	username = getpass.getuser()
	hostname = socket.getfqdn()
	smtp = smtplib.SMTP('localhost')
	smtp.ehlo()
	email_from = username + "@" + hostname
	http_host = os.environ.get('HTTP_HOST', hostname)
	msg = """From: %(email_from)s
To: %(email_to)s
Subject: comment on %(http_host)s/%(page)s
Context-Type: text/plain; charset=utf-8

%(comment)s
""" % vars()
	msg = msg.replace("\n", "\r\n")
	smtp.sendmail(email_from, email_to, msg)
	smtp.quit()

def main():
	os.chdir(os.environ["DOCUMENT_ROOT"])
	os.umask(0)

	form = cgi.FieldStorage()
	page = form.getvalue("page") or ''
	comment = form.getvalue("comment", "")
	if not page or not comment or not path_okay(page) or len(comment) > 10000:
		bad_request("missing or invalid args")

	send_comment_email(comments_email, page, comment)

	file_path = "comments/" + page
	comment = '<div class="comment">\n' + text_to_html(comment) + '\n</div>\n\n'
	append_comment(file_path, comment)

	headers()

	print comment

main()
